{{- if not .Values.mongodb.auth.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "save-the-mongoose.fullname" . }}-mongodb
  labels:
    {{- include "save-the-mongoose.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-password: {{ include "save-the-mongoose.rootPassword" . | b64enc | quote }}
  {{- if .Values.replication.enabled }}
  mongodb-replica-set-key: {{ include "save-the-mongoose.replicaSetKey" . | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.backup.enabled (not .Values.backup.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "save-the-mongoose.fullname" . }}-s3
  labels:
    {{- include "save-the-mongoose.labels" . | nindent 4 }}
type: Opaque
data:
  s3-access-key-id: {{ required "backup.s3.accessKeyId is required when backup is enabled" .Values.backup.s3.accessKeyId | b64enc | quote }}
  s3-secret-access-key: {{ required "backup.s3.secretAccessKey is required when backup is enabled" .Values.backup.s3.secretAccessKey | b64enc | quote }}
  {{- if .Values.backup.s3.endpoint }}
  s3-endpoint: {{ .Values.backup.s3.endpoint | b64enc | quote }}
  {{- end }}
{{- end }}
