name: Build and Push Docker Images

on:
  push:
    branches: ['main', 'master']
    paths:
      - 'docker/mongodb-backup-s3/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mongodb:
          - '4.4'
          - '5.0'
          - '6.0'
          - '7.0'
          - '8.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: rarup1/mongodb-backup-s3
          tags: |
            type=raw,value=${{ matrix.mongodb }}
            type=raw,value=latest,enable=${{ matrix.mongodb == '8.0' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/mongodb-backup-s3
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MONGODB_VERSION=${{ matrix.mongodb }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
