name: Release Charts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.0'

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .
          config: .github/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Sync README to gh-pages
        run: |
          # Save the tag name
          TAG_NAME=${GITHUB_REF#refs/tags/}

          # Checkout gh-pages branch
          git fetch origin gh-pages
          git checkout gh-pages

          # Copy README from the tag
          git checkout $TAG_NAME -- README.md

          # Commit and push
          git add README.md
          git commit -m "Sync README from $TAG_NAME" || echo "No changes to commit"
          git push origin gh-pages
